### ISSUE TITLE
Errors with new Input System changes?

### ISSUE THREAD

**Issue by mileswolf7** [akashenen/2d-platformer-controller#1]
I've noticed a few errors popping up with some of these scripts with the changes to the new input system. Anything with "using UnityEngine.Experimental.Input" will need to be changed to "using UnityEngine.InputSystem;"

There's still a few other errors popping up in the InputMaster and PlayerController scripts popping up that I'm trying to fix.

**Comment by mileswolf7** [comment]
InputActionAssetReference type missing

**Comment by mileswolf7** [comment]
controls.Player.Movement.cancelled 
controls.Player.Jump.cancelled

InputAction does not contain a reference for cancelled. 


** Deleting one in cancelled fixed the issue. 
controls.Player.Movement.canceled += ctx => Move(Vector2.zero);
controls.Player.Jump.canceled += EndJump;

**Comment by SandeMC** [comment]
There's still some errors in 2020, any help?

**Comment by JudgeGroovyman** [comment]
I got this totally working in 2019.2.11f1 2019.4.12f1:
1. The changes MilesWolf7 suggested above: The using and the cancelled
2. I had to use the package manager to import the InputSystem and Cinemachine (without cinemachine all of the demo scenes had errors)
3. In Project Settings->Player->Other->Active Input Handling I had to change to use the input system package (it did this switch for me in one case)
4. Had to add this line to the player controller awake `controls = new InputMaster();` (without that i had several null pointer errors and no inputs worked)
5. Delete the Assets/Input/InputMaster.cs (at least I had to do that because i dragged the whole repo into my project and when I imported the inputSystem there was another one of this file and the one that was imported was better than this one)

No errors and no warnings and the demo scenes work great!

**Comment by mr-tuduf** [comment]
nothing helps, could you post the you stable repo of 2d-platformer-controller?

**Comment by akashenen** [comment]
Hey guys! Sorry for the lack of updates. I became a VFX artist about 18 months ago, so my coding stuff got kinda neglected. Didn't even see these issues until now, oops! I have some vacations coming up soon so I'll try to at least fix all the errors and see if I can add any other features. Let me know if you find anything else!

**Comment by mr-tuduf** [comment]
This worked in Unity 2020. it was enough to change and add to PlayerController Awake `controls = new InputMaster ();` and change `using UnityEngine.Experimental.Input` to `using UnityEngine.InputSystem;`

The only thing I can't add my own animation, or rather the character's turn to the left, I can't figure out facingRight.
The animation plays to the right, while the animation to the left only unfolds the sprite. This is what I tried to add my Flip() code.
Can you tell me how to do this? I tried many options from the tutorials, but none of them work. :(

**Comment by akashenen** [comment]
I'll look into it!

**Comment by akashenen** [comment]
Fixed all the compilation errors, I'll look into the animation part in #2, so I'm closing this issue
