### ISSUE TITLE
Can't work in version 2020

### ISSUE THREAD

**Issue by SandeMC** [akashenen/2d-platformer-controller#3]
I fixed some errors but there's still two.

Assets\Input\InputMaster.cs(7,28): error CS0246: The type or namespace name 'InputActionAssetReference' could not be found (are you missing a using directive or an assembly reference?)

Assets\Input\InputMaster.cs(50,26): error CS0115: 'InputMaster.MakePrivateCopyOfActions()': no suitable method found to override

Any help?

**Comment by ALIAZEEM4** [comment]
I'm having the same issue

**Comment by JudgeGroovyman** [comment]
I just got this working great in 2020.1.11f1 (also in 2019.2.11f1 2019.4.12f1):

- The changes MilesWolf7 suggested in the other issue: 
	- in Assets/Scripts/PlayerController.cs change `using UnityEngine.Experimental.Input` to `using UnityEngine.InputSystem`
	- in the same file change the word `cancelled` to `canceled` in the lines that use: controls.Player.Movement.cancelled and controls.Player.Jump.cancelled
- I had to use the package manager to import the InputSystem and Cinemachine (without cinemachine all of the demo scenes had errors)
- In Project Settings->Player->Other->Active Input Handling I had to change to use the input system package (it did this switch for me in one case)
- Had to add this line to the player controller awake `controls = new InputMaster();` (without that i had several null pointer errors and no inputs worked)
- Delete the Assets/Input/InputMaster.cs (at least I had to do that because i dragged the whole repo into my project and when I imported the inputSystem there was another one of this file and the one that was imported was better than this one)

No errors and no warnings and the demo scenes work great!

**Comment by akashenen** [comment]
Will fix soon!

**Comment by akashenen** [comment]
Fixed
